name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */24 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: xMOROx
          outputs: | 
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.svg
      - name: checkout output branch
        uses: actions/checkout@v2
        with:
          ref: output
          path: output
      - name: copy output files
        run: |
          cp dist/github-contribution-grid-snake-dark.svg?palette=github-dark output/
          cp dist/github-contribution-grid-snake.svg output/
      - name: commit and push output files
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update snake animation"
          add: "output/"
          author_email: "actions@github.com"
          author_name: "GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          github_token: ${{ secrets.GITHUB_TOKEN }}
